# Generated by Django 3.1.7 on 2021-04-18 00:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('body', models.CharField(max_length=140)),
                ('Image', cloudinary.models.CloudinaryField(max_length=255)),
                ('like_count', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
