# Generated by Django 3.1.7 on 2021-04-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='updated_at',
        ),
    ]
