# Generated by Django 3.1.7 on 2021-05-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20210426_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='body',
        ),
        migrations.AddField(
            model_name='tweet',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='profile_img',
            field=models.FileField(default='blank', upload_to='profile/user'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_img',
            field=models.FileField(default='blank', upload_to='tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_text',
            field=models.CharField(default='blank', max_length=255),
        ),
        migrations.AddField(
            model_name='tweet',
            name='username',
            field=models.CharField(default='blank', max_length=20),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='name',
            field=models.CharField(default='blank', max_length=20),
        ),
    ]
