# Generated by Django 3.1.7 on 2021-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20210509_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
