# Generated by Django 3.1.7 on 2021-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_tweet_tweet_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
